name: Docker Push on Release

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: 'Docker Login'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/sentinel:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/sentinel:latest
          platforms: linux/amd64